### ISSUE TITLE
Support 1 million concurrent runs

### ISSUE THREAD

**Issue by johnstairs** [microsoft/tyger#112]
```[tasklist]
### Tasks
- [ ] #29
- [x] Allow tagging runs
- [x] Allow listing runs by status, buffers, and tags
- [ ] https://github.com/microsoft/tyger/issues/113
- [x] Improve run sweeper scalability
- [ ] Allow buffers to be (bulk) deleted
- [ ] https://github.com/microsoft/tyger/issues/114
- [ ] Display buffer status on `tyger buffer show`
- [x] Record time that a run started running
- [x] Expose endpoint to show counts of runs by status (filtered by tags)
- [ ] Handle deadlocking that can occur with dependent runs
- [ ] Use [gang scheduling](https://kubedl.io/docs/training/gangscheduling/) for distributed runs to avoid deadlocks
- [x] Set limit of number of Kubernetes jobs
```
