### ISSUE TITLE
OSS Release

### ISSUE THREAD

**Issue by johnstairs** [microsoft/tyger#63]
```[tasklist]
### Tasks
- [ ] #24
- [ ] https://github.com/microsoft/tyger/issues/64
- [ ] #25
- [x] Add copyright headers
- [x] Add copyright NOTICE file
- [ ] https://github.com/microsoft/tyger/issues/65
- [x] Remove ACR image from devcontainer.json
- [x] remove `clusters` from `tyger`
- [x] update threat model
- [x] Chain hash should use SHA-256
```
